/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import java.util.List;

public class ScrabbleTest {



@Test
public void calculateScoreForSingleLetter_1(){
  Scrabble testScrabble = new Scrabble();
  Integer expected =1;
  assertEquals(expected, testScrabble.calculateScore("A"));
}
@Test
public void calculateScoreForSingleLetter_2(){
  Scrabble testScrabble = new Scrabble();
  Integer expected =2;
  assertEquals(expected, testScrabble.calculateScore("D"));
}
@Test
public void calculateScoreForSingleLetter_3(){
  Scrabble testScrabble = new Scrabble();
  Integer expected =3;
  assertEquals(expected, testScrabble.calculateScore("B"));
}
@Test
public void calculateScoreForSingleLetter_4(){
  Scrabble testScrabble = new Scrabble();
  Integer expected =4;
  assertEquals(expected, testScrabble.calculateScore("F"));
}
@Test
public void calculateScoreForSingleLetter_5(){
  Scrabble testScrabble = new Scrabble();
  Integer expected =5;
  assertEquals(expected, testScrabble.calculateScore("k"));
}
@Test
public void calculateScoreForSingleLetter_8(){
  Scrabble testScrabble = new Scrabble();
  Integer expected =8;
  assertEquals(expected, testScrabble.calculateScore("J"));
}
@Test
public void calculateScoreForSingleLetter_10(){
  Scrabble testScrabble = new Scrabble();
  Integer expected =10;
  assertEquals(expected, testScrabble.calculateScore("Q"));
}
@Test
public void calculateScoreForAllAlpha_87(){
  Scrabble testScrabble = new Scrabble();
  Integer expected =87;
  assertEquals(expected, testScrabble.calculateScore("abcdefghijklmnopqrstuvwxyz"));
}


}
